//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLevel
{
    using System;
    
    public partial class UserResult
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public byte[] Hash { get; set; }
        public string Email { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> LastVisitDate { get; set; }
    }
}
